### ISSUE TITLE
Im constantly skipped whenever I am in the queue.

### ISSUE THREAD

**Issue by AnomalyJx** [matte-ek/BanchoMultiplayerBot#10]
I will run !qp / !q / !queue, to see my queue position and I find out I'm next in line. However once it reaches me I am kicked and the host is passed on to someone else, or my position is just abruptly reset. I've been in a lobby for about an hour and it has cycled to me about 3 times, and i haven't been given host. I'm just confused as to why.

**Comment by AnomalyJx** [comment]
sorry guys, i had autoskip on, gonna kms

**Comment by matte-ek** [comment]
Glad you got it sorted quickly. Maybe some sort of indicator to show that your auto-skip is enabled might be a good idea, since I doubt you're the only one who has done this, however I cannot really think of a clear, non-intrusive way of doing so. I'll see if I can come up with something.
