### ISSUE TITLE
Possibility for changing Port for Web

### ISSUE THREAD

**Issue by KannaDev** [matte-ek/BanchoMultiplayerBot#5]
So, something which can be added to `appsettings.json` is the ability to change the port which the Web GUI Binds too, as port 5000 is a port that many services use, it causes trouble for people running multiple services.

**Comment by matte-ek** [comment]
Hey, adding the following to your `appsettings.json` should do the trick:
```
"Urls": "http://localhost:5002"
```
Pretty sure this is also possible via environment variables using `ASPNETCORE_URLS=http://localhost:5002/`

**Comment by KannaDev** [comment]
Okay! Thanks for that, one issue I faced is that when logging in, it then brings up osu's OAUTH, which after approving, redirects to localhost rather than the domain, which is behind a reverse proxy.

**Comment by matte-ek** [comment]
Not sure what you are refering to here, as my bot does not (currently) use osu's OAuth anywhere. I've planned to replace the current authentication system to it, but haven't gotten around to doing it yet.

**Comment by KannaDev** [comment]
https://upload.kannadev.com/u/msedge_QQAA2fF4Kz.gif

**Comment by KannaDev** [comment]
![image](https://github.com/matte-ek/BanchoMultiplayerBot/assets/65371696/3a9323dc-24d5-4557-9f10-81386a3e0f7e)

**Comment by KannaDev** [comment]
![msedge_QQAA2fF4Kz](https://github.com/matte-ek/BanchoMultiplayerBot/assets/65371696/6fea01a4-f315-47d2-a842-36a025e832c5)

**Comment by matte-ek** [comment]
I'm so sorry, I just realized I might have released a build (v1.4.0) where I was experimenting with OAuth authentication within the bot, which I did around the time I released that. No clue how I managed to forget to remove that but here we are, my bad. The newest release I did today should have this fixed and should be behaving as normal.

**Comment by KannaDev** [comment]
No need to apologise, mistakes happen. Looking forward to it if it ends up releasing. Thanks for the quick response!

**Comment by KannaDev** [comment]
The WebUI now works perfectly fine, though I am unable to connect to Bancho with neither new or old api keys. And no logs.

**Comment by KannaDev** [comment]
![image](https://github.com/matte-ek/BanchoMultiplayerBot/assets/65371696/7d2ef1d9-4aa9-48eb-ac60-d21965e4f685)

**Comment by KannaDev** [comment]
Using the [following](https://github.com/Meowhal/osu-ahr) it is able to connect, and make lobbies. But not with your software.

**Comment by matte-ek** [comment]
I could reproduce, and to be honest with you I have no idea how I managed to upload a borked build twice.... I really need to reconsider this workflow (as I don't personally use the github releases), with maybe Github Actions testing and then publishing the builds, so they actually work. 

I replaced the binary in the newest release, and personally tested quickly on my machine to make sure they work properly, lol. If you need any further support feel free to contact me on Discord "matte # 4873". Sorry for wasting your time.

**Comment by KannaDev** [comment]
It's all fine, and you're not wasting my time in any way at all, these things happen and i've been in the same situation as this, instead of treating it as a negative experience, it's a way to learn and make sure things like this don't happen. GitHub actions could be a good way at testing. And I will now test the newest release. And if I do, I'll let you know.

**Comment by KannaDev** [comment]
Closing this issue as all is now resolved, looking forward to see future updates, and love the project!
