### ISSUE TITLE
How can I login via ip

### ISSUE THREAD

**Issue by nise2511** [matte-ek/BanchoMultiplayerBot#8]
Can I login via ip or does it only work for localhost?
![Untitled](https://github.com/matte-ek/BanchoMultiplayerBot/assets/140241321/f5d8c9ed-ef9e-492f-aeb0-fccfcb53adb8)

**Comment by matte-ek** [comment]
Hey, by default it only listens on localhost, yes. However you can change this by adding the following to your appsettings.json:
```
"Urls": "http://0.0.0.0:5000"
```

**Comment by nise2511** [comment]
It work but now I can't login idk why
![233003](https://github.com/matte-ek/BanchoMultiplayerBot/assets/140241321/5889b2f0-0010-4872-b765-2f409a2fdaa5)

**Comment by matte-ek** [comment]
You probably aren't on `/osu-bot`.

**Comment by nise2511** [comment]
Ahh ok thank you
