### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by Bibou1494** [matte-ek/BanchoMultiplayerBot#9]
Hello. So now with a update now i can't run and i'm still in 32 bits so i still can't run the .exe and i need to run with the terminal but now i got this error
```
$ dotnet BanchoMultiplayerBot.Host.Web.dll
Unhandled exception. System.BadImageFormatException: Could not load file or assembly '$ \release (3)\BanchoMultiplayerBot.Host.Web.dll'. Format of the executable (.exe) or library (.dll) is invalid.
File name: '$ \release (3)\BanchoMultiplayerBot.Host.Web.dll
```
![why_](https://github.com/matte-ek/BanchoMultiplayerBot/assets/132447113/fd673710-b508-412f-a6f2-2cab3e5e04c6)
can you help me ?

**Comment by matte-ek** [comment]
Not too sure, but seems like the latest release I did was missing some binaries, so you could try with the new release. 

~~Yet another reason to setup publish pipelines, one day...~~

**Comment by Bibou1494** [comment]
Ok I gonna try

**Comment by Bibou1494** [comment]
Thanks it's like it's work so thanks
